name: build-raja

inputs:
  raja-url:
    description: 'URL where to look for RAJA'
    required: false
    default: 'https://github.com/LLNL/RAJA/archive'
  raja-archive:
    description: 'Archive to download'
    required: true
  raja-dir:
    description: 'RAJA top directory name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install RAJA
      run: |
        wget --no-verbose ${{ inputs.raja-url }}/${{ inputs.raja-archive }};
        rm -rf ${{ inputs.raja-dir }};
        tar -xzf ${{ inputs.raja-archive }};
        mv ${{ inputs.raja-archive }} ${{ inputs.raja-dir }};
        cd ${{ inputs.raja-dir }};
        mkdir build;
        cd build;
        cmake ../ -DCMAKE_INSTALL_PREFIX=${{ inputs.raja-dir }}/install_dir/ \
                  -DENABLE_OPENMP=OFF \
                  -DENABLE_CUDA=OFF \
                  -DENABLE_TESTS=OFF \
                  -DRAJA_TIMER=chrono \
                  -DCMAKE_BUILD_TYPE=Release 
        make -j3;
        make install;
      shell: bash