name: build-raja

inputs:
  raja-repo:
    description: 'URL where to look for ExaCMech'
    required: false
    default: 'https://github.com/llnl/RAJA.git'
  raja-dir:
    description: 'RAJA top directory name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install RAJA
      run: |
        git clone --single-branch --branch v0.11.0 --depth 1 ${{ inputs.raja-repo }} ${{ inputs.raja-dir }};
        cd ${{ inputs.raja-dir }};
        mkdir build;
        cd build;
        cmake ../ -DCMAKE_INSTALL_PREFIX=../install_dir/ \
                  -DENABLE_OPENMP=OFF \
                  -DENABLE_CUDA=OFF \
                  -DENABLE_TESTS=OFF \
                  -DRAJA_TIMER=chrono \
                  -DCMAKE_BUILD_TYPE=Release 
        make -j3;
        make install;
      shell: bash