name: build-ecmech

inputs:
  ecmech-repo:
    description: 'URL where to look for ExaCMech'
    required: false
    default: 'https://github.com/LLNL/ExaCMech.git'
  ecmech-dir:
    description: 'ExaCMech top directory name'
    required: true
  raja-dir:
    description: 'raja install location working dir'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install ECMech
      run: |
        git clone --single-branch --branch develop --depth 1 ${{ inputs.ecmech-repo }} ${{ inputs.ecmech-dir }};
        cd ${{ inputs.ecmech-dir }};
        git submodule init;
        git submodule update;
        mkdir build;
        cd build;
        echo ${{ inputs.raja-dir }}
        cmake ../ -DCMAKE_INSTALL_PREFIX=../install_dir/ \
                  -DRAJA_DIR=${{ inputs.raja-dir }} \
                  -DENABLE_OPENMP=OFF \
                  -DENABLE_CUDA=OFF \
                  -DENABLE_TESTS=OFF \
                  -DCMAKE_BUILD_TYPE=Release 
        make -j3;
        make install;
      shell: bash